Update acceptable Visium barcodes and allow an updated list to be given
pachterlab/SpatialFeatureExperiment pull request #46
Opened 2024-07-10 05:49 UTC by newmana

This updates sysdata.rda to version 4 of the list of barcodes that are valid (https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist) and adds to read10xVisiumSFE an optional dataframe that contains barcode, col, row.

2024-07-10 06:04 UTC, OnkarMulay commented
👍

2024-07-18 09:42 UTC, newmana commented
Just updated by adding v1-v5 of the barcodes into data, warnings/error when barcodes are removed, and note dnearneigh throws an exception if any barcodes are removed.

2024-07-22 09:12 UTC, lambdamoses requested changes
Thank you for the PR! So far it mostly looks good. Please make sure to update the documentation for the data as well in this file: https://github.com/pachterlab/SpatialFeatureExperiment/blob/main/R/data.R. Also Bioconductor discourages `LazyData: true` but if the `visium_row_col_v*` files are small enough it should be fine.

2024-07-22 09:13 UTC, lambdamoses approved these changes

2024-07-22 09:14 UTC, lambdamoses commented on inst/script/visium_row_col.R
You should also commit the new `visium_row_col_v*.rda` files in the `data` directory

2024-07-22 09:27 UTC, lambdamoses commented on R/read.R
Shouldn't `barcode_allow_list` be used to filter the gene count matrix and spot metadata first?

2024-07-22 09:30 UTC, lambdamoses commented on R/read.R
I also wonder if there's a way to automatically determine the Space Ranger version whitelist so users don't have to manually supply the list, even from data within this package.

2024-07-22 09:34 UTC, lambdamoses commented on R/read.R
Or use an argument like `whitelist_version` and have some internal code pull up the whitelist so the user doesn't have to call `data(visium_row_col_v5)` first.

2024-07-23 01:19 UTC, newmana commented on R/read.R
I'm not sure what you mean by: "Shouldn't barcode_allow_list be used to filter the gene count matrix and spot metadata first?"

For automatic detection, I looked the various files that are part of the Mouse Olfactory and the samples I'm using and I couldn't see anything that lined up to what's correct. The visium mouse bulb, the matrix has:
```
%metadata_json: {"software_version": "Space Ranger spaceranger-2.0.0", "format_version": 2}
```

And the files that I have that fail contain:
```
%metadata_json: {"software_version": "spaceranger-2.1.0", "format_version": 2}
```

So I haven't been able to find a way to automatically detect it. 

It might work better the other way around - go through the list of valid barcodes to detect the version of the file?

I did think of that of adding that - but do you create a closed set of v1-v5 options - what about version v6? It really depends on whether you want to keep this updated or not.

2024-07-23 01:20 UTC, newmana commented on inst/script/visium_row_col.R
Thanks I've added that.

2024-07-23 01:29 UTC, newmana commented on R/read.R
"I did think of that of adding that - but do you create a closed set of v1-v5 options - what about version v6? It really depends on whether you want to keep this updated or not." - related to using a whitelist_version parameter instead. I don't think it's obvious what version of the file you're using.

2024-07-25 00:48 UTC, newmana commented
I have an alternative suggestion. When adding a parameter to so many functions it’s potentially a sign of the feature being at the right level. Maybe remove it from where it is an assume calls already have valid barcode and add a separate function to check it.

2024-07-29 22:02 UTC, lambdamoses commented
> I have an alternative suggestion. When adding a parameter to so many functions it’s potentially a sign of the feature being at the wrong level. Maybe remove it from where it is and assume calls already have valid barcodes and add a separate function to check it.

Sounds good. How often does Space Ranger output have invalid barcodes? If it's not very often then this approach is more reasonable.

2024-07-29 22:05 UTC, lambdamoses commented on R/read.R
> I did think of that of adding that - but do you create a closed set of v1-v5 options - what about version v6?

What about having one argument for version numbers that are used internally to get the list from the package's internal data, and another rarely used argument to directly supply the list when a custom list or a version not yet supported is desired? Either way we have to keep the package updated when v6 comes out, to add the v6 list to the package data or the user would have to find the v6 list somewhere else.

2024-07-29 23:05 UTC, newmana commented
Okay. I've processed > 50 different samples now and haven't ever seen Space Ranger produce invalid bar codes. Will try again with another PR.

2024-07-29 23:05 UTC, closed without merging